/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shz_videodecode_Player */

#ifndef _Included_com_shz_videodecode_Player
#define _Included_com_shz_videodecode_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shz_videodecode_Player
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_shz_videodecode_Player_play
  (JNIEnv *env, jclass jcls, jstring,jobject surface);

#ifdef __cplusplus
}
#endif
#endif
